ARG vllm_version=v0.12.0

FROM docker.io/vllm/vllm-openai:${vllm_version}

# For audio
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system librosa soundfile mistral_common[audio]

COPY / /middleware

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=/,target=/middleware,relabel=shared \
    uv pip install --system /middleware

WORKDIR /home/vllm
ENV HOME=/home/vllm
RUN useradd --home-dir /home/vllm --gid 0 \
    --no-create-home --shell /bin/bash vllm && \
    chmod 775 /home/vllm

USER vllm
